name: Pr_Ci

on:
  pull_request:
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  validate:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Activate melos
        run: dart pub global activate melos
      - name: Bootstrap melos
        run: melos bs
      - name: Validate code
        run: melos run validate
      - name: Test code
        run: melos run test
      - name: Activate coverage
        run: dart pub global activate coverage
      - name: Run coverage
        run: melos run lcov